### ISSUE TITLE
How to define a target path by myself.

### ISSUE THREAD

**Issue by Li-Jun-SD** [tier4/caret#52]
Is it possible to define a target path by change architecture.yaml? I tried `paths = arch.search_paths()`, notebook busy forever..., no target_path is created.

**Comment by Li-Jun-SD** [comment]
```
---------------------------------------------------------------------------
ItemNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_148960/2255407313.py in <module>
      1 from caret_analyze.plot import message_flow
      2 
----> 3 path = app.get_path('target_path')
      4 message_flow(path)

~/ros2_caret_ws/build/caret_analyze/caret_analyze/runtime/application.py in get_path(self, path_name)
    209             return x.path_name
    210 
--> 211         return Util.find_similar_one(path_name,
    212                                      self.paths,
    213                                      get_name)

~/ros2_caret_ws/build/caret_analyze/caret_analyze/common/util.py in find_similar_one(target_name, items, key, th)
    130             raise ItemNotFoundError(msg)
    131         else:
--> 132             raise ItemNotFoundError('Failed find item.')
    133 
    134     @staticmethod

ItemNotFoundError: Failed find item.
```

**Comment by Li-Jun-SD** [comment]
```
named_paths:
- path_name: target_path
  node_chain:
  - node_name: /planning/mission_planning/mission_planner
    publish_topic_name: /planning/mission_planning/route
    subscribe_topic_name: UNDEFINED
  - node_name: /system/ad_service_state_monitor
    publish_topic_name: /autoware/state
    subscribe_topic_name: /planning/mission_planning/route
  - node_name: /system/system_error_monitor
    publish_topic_name: /system/emergency/hazard_status
    subscribe_topic_name: /autoware/state
  - node_name: /system/emergency_handler
    publish_topic_name: /system/emergency/hazard_lights_cmd
    subscribe_topic_name: /system/emergency/hazard_status
  - node_name: /control/vehicle_cmd_gate
    publish_topic_name: /control/command/turn_indicators_cmd
    subscribe_topic_name: /system/emergency/hazard_lights_cmd
  - node_name: /simulation/simple_planning_simulator
    publish_topic_name: /localization/kinematic_state
    subscribe_topic_name: /control/command/turn_indicators_cmd
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner
    publish_topic_name: UNDEFINED
    subscribe_topic_name: /localization/kinematic_state
```
